language: node_js
node_js:
  - '10'
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  project: ./.storybook-build/
  local_dir: ./.storybook-build/
  on:
    branch: master
